# Generated by Django 3.2 on 2024-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('publicador', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('tamanio', models.IntegerField()),
                ('costo', models.IntegerField()),
            ],
        ),
    ]
