# Generated by Django 3.2 on 2024-11-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaApp', '0002_auto_20241104_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
    ]
